-- AlterTable
ALTER TABLE "ShopBanner" ADD COLUMN     "amount1Star" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "amount2Star" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "amount3Star" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "amount4Star" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "amount5Star" INTEGER NOT NULL DEFAULT 0;
