export const AchievementTierType = {
  BASIC: 'BASIC',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
  MASTER: 'MASTER'
} as const

export type AchievementTierTypeType = keyof typeof AchievementTierType

export const AchievementType = {
  COMPLETE_LESSON: 'COMPLETE_LESSON',
  CHOOSE_STARTER_POKEMON: 'CHOOSE_STARTER_POKEMON',
  PLACEMENT_TEST_DONE: 'PLACEMENT_TEST_DONE',
  LEARNING_STREAK: 'LEARNING_STREAK',
  CAPTURE_POKEMON_COUNT: 'CAPTURE_POKEMON_COUNT',
  CAPTURE_TYPE_COLLECTION: 'CAPTURE_TYPE_COLLECTION',
  CAPTURE_ALL_POKEMON: 'CAPTURE_ALL_POKEMON',
  CAPTURE_LEGENDARY: 'CAPTURE_LEGENDARY',
  EVOLVE_POKEMON_FINAL: 'EVOLVE_POKEMON_FINAL'
} as const

export type AchievementTypeType = keyof typeof AchievementType
